/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ENSCheckAvailability,
  ENSCheckAvailabilityInterface,
} from "../ENSCheckAvailability";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_label",
        type: "uint256",
      },
    ],
    name: "checkAvailability",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60806040527357f1887a8bf19b14fc0df6fd9b2acc9af147ea856000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555034801561006457600080fd5b5061026a806100746000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063753999ef14610030575b600080fd5b61004a6004803603810190610045919061016a565b610060565b60405161005791906101b5565b60405180910390f35b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166396e494e8836040518263ffffffff1660e01b81526004016100bc91906101d0565b60206040518083038186803b1580156100d457600080fd5b505afa1580156100e8573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061010c919061013d565b9050919050565b60008151905061012281610206565b92915050565b6000813590506101378161021d565b92915050565b60006020828403121561015357610152610201565b5b600061016184828501610113565b91505092915050565b6000602082840312156101805761017f610201565b5b600061018e84828501610128565b91505092915050565b6101a0816101eb565b82525050565b6101af816101f7565b82525050565b60006020820190506101ca6000830184610197565b92915050565b60006020820190506101e560008301846101a6565b92915050565b60008115159050919050565b6000819050919050565b600080fd5b61020f816101eb565b811461021a57600080fd5b50565b610226816101f7565b811461023157600080fd5b5056fea2646970667358221220d461f216e0bcb94e2070e362c174999eaf2df445540275356655ed58eb07c72564736f6c63430008070033";

export class ENSCheckAvailability__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ENSCheckAvailability> {
    return super.deploy(overrides || {}) as Promise<ENSCheckAvailability>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ENSCheckAvailability {
    return super.attach(address) as ENSCheckAvailability;
  }
  connect(signer: Signer): ENSCheckAvailability__factory {
    return super.connect(signer) as ENSCheckAvailability__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ENSCheckAvailabilityInterface {
    return new utils.Interface(_abi) as ENSCheckAvailabilityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ENSCheckAvailability {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ENSCheckAvailability;
  }
}
