/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IBaseRegistrar,
  IBaseRegistrarInterface,
} from "../IBaseRegistrar";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "label",
        type: "uint256",
      },
    ],
    name: "available",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBaseRegistrar__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseRegistrarInterface {
    return new utils.Interface(_abi) as IBaseRegistrarInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBaseRegistrar {
    return new Contract(address, _abi, signerOrProvider) as IBaseRegistrar;
  }
}
